#!/usr/bin/env python3
"""
Distributed Training Adapter: NCCL -> HCCL

Converts distributed training configurations from NVIDIA NCCL backend
to Huawei HCCL backend for Ascend 910B multi-card training.

This script generates the correct launch commands and configuration files
for running distributed training on Ascend 910B.

Usage:
    python distributed_adapter.py --cards 8 --nnodes 1 --node-rank 0 --master-addr 127.0.0.1

    # Generate launch script for single node 8-card training
    python distributed_adapter.py --cards 8 --generate-launch-script train.sh
"""

import argparse
import sys


def generate_torchrun_command(args) -> str:
    """Generate torchrun command for Ascend NPU distributed training."""
    cmd_parts = [
        "torchrun",
        f"    --nproc_per_node={args.cards}",
        f"    --nnodes={args.nnodes}",
        f"    --node_rank={args.node_rank}",
        f"    --master_addr={args.master_addr}",
        f"    --master_port={args.master_port}",
    ]

    cmd = " \\\n".join(cmd_parts)
    cmd += f" \\\n    {args.training_script}"

    if args.training_args:
        cmd += f" \\\n    {args.training_args}"

    return cmd


def generate_launch_script(args) -> str:
    """Generate a complete bash script for distributed training."""
    script = f"""#!/bin/bash
# =============================================================================
# Distributed Training Launch Script for Ascend 910B
# Auto-generated by distributed_adapter.py
# =============================================================================

set -euo pipefail

# ---- Configuration ----
NPU_DEVICES="{','.join(str(i) for i in range(args.cards))}"
MASTER_ADDR="{args.master_addr}"
MASTER_PORT="{args.master_port}"
WORLD_SIZE={args.nnodes * args.cards}
RANK={args.node_rank}

echo "========================================"
echo "  Distributed Training on Ascend 910B"
echo "========================================"
echo "  NPU devices:  {NPU_DEVICES}"
echo "  World size:   {WORLD_SIZE}"
echo "  Node rank:    {RANK}"
echo "  Master:       {MASTER_ADDR}:{MASTER_PORT}"
echo "========================================"

# ---- Check NPU availability ----
echo ""
echo "Checking NPU devices..."
npu-smi info

# ---- Set environment variables ----
export ASCEND_RT_VISIBLE_DEVICES={NPU_DEVICES}
export MASTER_ADDR={MASTER_ADDR}
export MASTER_PORT={MASTER_PORT}
export WORLD_SIZE={WORLD_SIZE}
export RANK={RANK}

# ---- HCCL communication settings ----
export HCCL_CONNECT_TIMEOUT=120
export HCCL_EXEC_TIMEOUT=0
export HCCL_BUFFSIZE=8

# ---- Memory optimization ----
export PYTORCH_NPU_ALLOC_CONF="expandable_segments:True"

# ---- Launch distributed training ----
echo ""
echo "Launching distributed training..."
echo ""

{generate_torchrun_command(args)}
"""
    return script


def generate_config_code(args) -> str:
    """Generate Python code snippet for distributed initialization."""
    code = f'''
# =============================================================================
# Add this to your training script for HCCL distributed training
# =============================================================================

import os
import torch
import torch_npu  # Must import torch_npu BEFORE distributed init
import torch.distributed as dist


def setup_distributed():
    """Initialize HCCL distributed training group."""
    # Read environment variables set by torchrun
    rank = int(os.environ.get("RANK", 0))
    world_size = int(os.environ.get("WORLD_SIZE", 1))
    local_rank = int(os.environ.get("LOCAL_RANK", 0))

    # Initialize process group with HCCL backend
    dist.init_process_group(
        backend="hccl",  # <-- Changed from "nccl" to "hccl"
        init_method="env://",
        world_size=world_size,
        rank=rank,
    )

    # Set current device
    torch.npu.set_device(local_rank)

    print(f"Rank {{rank}}/{{world_size}} initialized on NPU:{{local_rank}}")
    return rank, world_size, local_rank


def cleanup_distributed():
    """Clean up distributed training group."""
    if dist.is_initialized():
        dist.destroy_process_group()


def wrap_model_for_distributed(model):
    """Wrap model for distributed training on NPU."""
    local_rank = int(os.environ.get("LOCAL_RANK", 0))
    model = model.to(f"npu:{{local_rank}}")
    model = torch.nn.parallel.DistributedDataParallel(
        model,
        device_ids=[local_rank],
        output_device=local_rank,
        broadcast_buffers=False,  # Set True if using BatchNorm
    )
    return model


# =============================================================================
# Usage in your training script:
# =============================================================================
#
# if __name__ == "__main__":
#     rank, world_size, local_rank = setup_distributed()
#
#     model = MyModel()
#     model = wrap_model_for_distributed(model)
#
#     # Training loop...
#     for epoch in range(num_epochs):
#         for batch in dataloader:
#             # ...
#             pass
#
#     cleanup_distributed()
#
# =============================================================================
# Launch command (from generated script):
# =============================================================================
#
# {generate_torchrun_command(args)}
#
'''
    return code


def main():
    parser = argparse.ArgumentParser(
        description='Distributed Training Adapter: NCCL -> HCCL for Ascend 910B'
    )
    parser.add_argument('--cards', type=int, default=8,
                        help='Number of NPU cards per node (default: 8)')
    parser.add_argument('--nnodes', type=int, default=1,
                        help='Number of nodes (default: 1)')
    parser.add_argument('--node-rank', type=int, default=0,
                        help='Rank of this node (default: 0)')
    parser.add_argument('--master-addr', type=str, default='127.0.0.1',
                        help='Master node address (default: 127.0.0.1)')
    parser.add_argument('--master-port', type=str, default='29500',
                        help='Master node port (default: 29500)')
    parser.add_argument('--training-script', type=str, default='train.py',
                        help='Training script to run (default: train.py)')
    parser.add_argument('--training-args', type=str, default='',
                        help='Additional arguments for training script')
    parser.add_argument('--generate-launch-script', type=str,
                        help='Generate launch script and save to file')
    parser.add_argument('--generate-config', action='store_true',
                        help='Generate Python config code for training script')

    args = parser.parse_args()

    # Show summary
    print("=" * 60)
    print("  Distributed Training Configuration for Ascend 910B")
    print("=" * 60)
    print(f"  Cards per node:  {args.cards}")
    print(f"  Number of nodes: {args.nnodes}")
    print(f"  World size:      {args.nnodes * args.cards}")
    print(f"  Backend:         HCCL (Huawei Collective Communication)")
    print("=" * 60)

    # Generate launch script
    if args.generate_launch_script:
        script = generate_launch_script(args)
        with open(args.generate_launch_script, 'w') as f:
            f.write(script)
        print(f"\nLaunch script saved to: {args.generate_launch_script}")
        print("Run: chmod +x {args.generate_launch_script}")

    # Generate Python config
    if args.generate_config:
        code = generate_config_code(args)
        print(code)

    # Print torchrun command
    print("\nDirect torchrun command:")
    print("-" * 40)
    print(generate_torchrun_command(args))
    print("-" * 40)

    # Key differences NCCL -> HCCL
    print("\nKey changes needed in your training code:")
    print("  1. import torch_npu  (add before distributed init)")
    print('  2. backend="nccl" -> backend="hccl"')
    print('  3. device="cuda" -> device="npu"')
    print('  4. torch.cuda.* -> torch.npu.*')
    print('  5. CUDA_VISIBLE_DEVICES -> ASCEND_RT_VISIBLE_DEVICES')
    print()


if __name__ == '__main__':
    main()
